# -*- coding: utf-8 -*-
"""Deploy_Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZL3YRL7VCY_9In0y2DG9CJlg3YILJiU

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

# =========================
# LIBRARIES
# =========================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# =========================
# LOAD MODEL
# =========================

import pickle
filename = 'modelo_final.pkl'

with open(filename, 'rb') as f:
    modelo, scaler, variables = pickle.load(f)

#Cargamos los datos futuros
# data = pd.read_csv("videojuegos-datosFuturos.csv")
# data.head()

# =========================
# PAGE CONFIG
# =========================

import streamlit as st

st.set_page_config(
    page_title='Predicción Precio Energía',
    layout='wide'
)

# =========================
# TITLE
# =========================

st.title('Predicción del precio de energía d+1')

st.write(
    'Cargue un archivo CSV con la estructura requerida para realizar las predicciones.'
)

# =========================
# EXPECTED STRUCTURE
# =========================

st.subheader('Estructura requerida del archivo CSV')

estructura = pd.DataFrame({
    'Variable': [
        'periodo',
        'mes',
        'Generación_kWh',
        'Demanda_No_Atendida_kWh',
        'Exportaciones_kWh',
        'Importaciones_kWh',
        'Volumen_Mm³',
        'Aportes_Caudal_m3/s',
        'Mínimo_Generación_Hidraulica_kWh',
        'delta_reservas_7d',
        'regimen_enso'
    ],
    'Tipo': [
        'float',
        'float',
        'float',
        'float',
        'float',
        'float',
        'float',
        'float',
        'float',
        'float',
        'categoria'
    ],
    'Ejemplo': [
        2024,
        5,
        1500000,
        0,
        12000,
        3000,
        500,
        700,
        200000,
        -5,
        'Niño'
    ]
})

st.dataframe(estructura, use_container_width=True)

# =========================
# FILE UPLOADER
# =========================

uploaded_file = st.file_uploader(
    'Cargue el archivo CSV',
    type=['csv']
)

"""# Predicciones"""

# =========================
# PREDICTION PROCESS
# =========================

if uploaded_file is not None:

    # =========================
    # READ CSV
    # =========================

    data = pd.read_csv(uploaded_file)

    st.subheader('Datos cargados')
    st.dataframe(data.head(), use_container_width=True)

    # =========================
    # PREPROCESSING
    # =========================

    data_preparada = data.copy()

    # DUMMIES

    data_preparada = pd.get_dummies(
        data_preparada,
        columns=['regimen_enso'],
        drop_first=True,
        dtype=int
    )

    # REINDEX

    data_preparada = data_preparada.reindex(
        columns=variables,
        fill_value=0
    )

    # NUMERIC COLUMNS

    numeric_cols = [
        'periodo',
        'mes',
        'Generación_kWh',
        'Demanda_No_Atendida_kWh',
        'Exportaciones_kWh',
        'Importaciones_kWh',
        'Volumen_Mm³',
        'Aportes_Caudal_m3/s',
        'Mínimo_Generación_Hidraulica_kWh',
        'delta_reservas_7d'
    ]

    # SCALING

    data_preparada[numeric_cols] = scaler.transform(
        data_preparada[numeric_cols]
    )

    # =========================
    # PREDICTIONS
    # =========================

    predicciones = modelo.predict(data_preparada)

    # =========================
    # RESULTS
    # =========================

    data['Prediccion_precio_d+1'] = predicciones

    st.subheader('Predicciones realizadas')

    st.dataframe(data, use_container_width=True)

    # =========================
    # DOWNLOAD CSV
    # =========================

    csv = data.to_csv(index=False).encode('utf-8')

    st.download_button(
        label='Descargar predicciones CSV',
        data=csv,
        file_name='predicciones_energia.csv',
        mime='text/csv'
    )

    # =========================
    # SUCCESS MESSAGE
    # =========================

    st.success('Predicciones generadas correctamente')

# =========================
# MODEL ERROR (recordar de la medida de error del modelo)
# =========================

st.subheader('Desempeño del modelo')

st.info(
    'Error promedio del modelo (MAPE): 1.07%'
)

st.write(
    'El MAPE representa el porcentaje promedio de error de las predicciones del modelo.'
)